# Generated by Django 5.0.3 on 2024-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desctiption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
