# Generated by Django 5.0.3 on 2024-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_banner_desctiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
