# Generated by Django 5.0.3 on 2024-03-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_banner_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Slider',
        ),
    ]
