# Generated by Django 5.0.3 on 2024-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_banner_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
